### ISSUE TITLE
HostsEdit shortcut overrides Linux's `replace_next` shortcut

### ISSUE THREAD

**Issue by twolfson** [martinssipenko/SublimeHostsEdit#6]
I cannot use the default `replace_next` key binding as it is being overridden by HostsEdit. It would be nicer if this were a command in the Command Palette instead of setting a key binding.

**Comment by Bogardo** [comment]
Probably a little late to the party...
You should be able to override any key bindings within `Key Bindings - User`.
Also, the 'Open Hosts File' command is in fact available in the Command Palette.
