### ISSUE TITLE
No Valid Semver Tags

### ISSUE THREAD

**Issue by wbond** [martinssipenko/SublimeHostsEdit#7]
Your entry in https://github.com/wbond/package_control_channel/blob/master/repository/h.json indicates you are providing releases via semver tags, however you don't have any tags that are valid semvers. http://semver.org/

Because of this, your package is not available to anyone via Package Control.

**Comment by Bogardo** [comment]
@martinssipenko Please tag a 1.0.0 version. This package is awesome but unfortunately not available anymore in Package Control.

**Comment by Bogardo** [comment]
This has been fixed. See: https://github.com/wbond/package_control_channel/issues/3184
